name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
    build:
        name: Build and test
        runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
        strategy:
            matrix:
              dotnet-version: [ '8.0.x' ]
        steps:
            - uses: actions/checkout@v4
            - name: Setup dotnet ${{ matrix.dotnet-version }}
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: ${{ matrix.dotnet-version }}
                # You can test your matrix by printing the current dotnet version
            - name: Display dotnet version
              run: dotnet --version

            - name: create the dotnet build
              run: dotnet build

            - name: install npm in the DotnetTemplate.Web directory
              run: npm install
              working-directory: DotnetTemplate.Web

            - name: execute the scripts in the DotnetTemplate.Web directory
              run: npm run build
              working-directory: DotnetTemplate.Web
